# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'relay-server'
primary_region = 'sjc'
kill_signal = 'SIGTERM'
kill_timeout = '5m0s'

[experimental]
  auto_rollback = true

[build]

[env]
  Y_SWEET_STORE = '/data'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
