#
# Tailscale-enabled docker-compose for Relay Server with MinIO
#
# Required environment variables:
# TS_AUTHKEY - Tailscale auth key
# RELAY_SERVER_AUTH - Auth token from Relay team
# RELAY_SERVER_URL_PREFIX - Tailscale URL for relay server (e.g., http://relay-server.tailnet.ts.net:8080)
# AWS_ENDPOINT_URL_S3 - Tailscale URL for MinIO (should match RELAY_SERVER_URL_PREFIX but port 9000)
#
# Example configuration:
# RELAY_SERVER_URL_PREFIX=http://relay-server.mytailnet.ts.net:8080
# AWS_ENDPOINT_URL_S3=http://relay-server.mytailnet.ts.net:9000
#

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: relay-tailscale
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY:?}
      - TS_TAILSCALED_EXTRA_ARGS=--tun=tailscale1
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - tailscale-state:/var/lib/tailscale
    restart: unless-stopped
    ports:
      - 8080:8080 # relay-server
      - 9000:9000 # minio API - required for client access to presigned URLs
      - 9091:9091 # minio console

  minio:
    container_name: minio
    network_mode: 'service:tailscale'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - ./data:/data/relaymd
    restart: unless-stopped
    entrypoint: sh
    command: -c 'mkdir -p /data/relaymd && /usr/bin/minio server /data --console-address ":9001"'
    image: quay.io/minio/minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  relay-server:
    image: docker.system3.md/relay-server:latest
    container_name: relay-server
    network_mode: 'service:tailscale'
    environment:
      - AWS_S3_USE_PATH_STYLE=true
      - AWS_ENDPOINT_URL_S3=${AWS_ENDPOINT_URL_S3:-http://localhost:9000}
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER:-minioadmin}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
      - RELAY_SERVER_STORAGE=${RELAY_SERVER_STORAGE:-s3://relaymd}
      - RELAY_SERVER_AUTH=${RELAY_SERVER_AUTH:?}
      - RELAY_SERVER_URL_PREFIX=${RELAY_SERVER_URL_PREFIX}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ready"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

volumes:
  tailscale-state:
