apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "{{ .Chart.Name }}"
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Chart.Name }}"
    spec:
      containers:
      - name: "{{ .Chart.Name }}"
        image: "{{ .Values.image.repository }}/{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        resources: {{ toYaml .Values.resources | nindent 10 }}
        env:
        # Public URL for your service
        - name: RELAY_SERVER_URL
          value: "{{ .Values.env.relayServerUrl }}"
        # S3 storage
        - name: RELAY_SERVER_STORAGE
          value: "{{ .Values.env.relayServerStorage }}"
        {{- if .Values.env.awsRegion }}
        - name: AWS_REGION
          value: "{{ .Values.env.awsRegion }}"
        {{- end }}
        {{- if .Values.env.awsEndpointUrlS3 }}
        - name: AWS_ENDPOINT_URL_S3
          value: "{{ .Values.env.awsEndpointUrlS3 }}"
        {{- end }}
        {{- if .Values.env.awsS3UsePathStyle }}
        - name: AWS_S3_USE_PATH_STYLE
          value: "{{ .Values.env.awsS3UsePathStyle }}"
        {{- end }}
        # Secret env vars from KeyVault
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.name }}-aws-access-key"
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.name }}-aws-secret-key"
              key: AWS_SECRET_ACCESS_KEY
