apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: "{{ .Values.name }}-auth-token"
spec:
  vault:
    name: {{ .Values.azure.keyVault.name }}
    object:
      name: obsidian-relay-server-auth-token
      type: secret
  output:
    secret:
      name: "{{ .Values.name }}-auth-token"
      dataKey: Y_SWEET_AUTH
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: "{{ .Values.name }}-aws-access-key"
spec:
  vault:
    name: {{ .Values.azure.keyVault.name }}
    object:
      name: obsidian-relay-server-aws-access-key
      type: secret
  output:
    secret:
      name: "{{ .Values.name }}-aws-access-key"
      dataKey: AWS_ACCESS_KEY_ID
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: "{{ .Values.name }}-aws-secret-key"
spec:
  vault:
    name: {{ .Values.azure.keyVault.name }}
    object:
      name: obsidian-relay-server-aws-secret-key
      type: secret
  output:
    secret:
      name: "{{ .Values.name }}-aws-secret-key"
      dataKey: AWS_SECRET_ACCESS_KEY
