apiVersion: v1
kind: Service
metadata:
  name: "{{ include "{{ .Chart.Name }}.fullname" . }}"
  labels: {{ include "{{ .Chart.Name }}.commonLabels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector: {{ include "{{ .Chart.Name }}.appLabel" . | nindent 4 }}
